# This file is generated by `engels doctor`. Do not edit by hand.

cmake_minimum_required(VERSION 3.20)

project(ecosystem_doctor_probe LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD {{cpp_standard}})
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

{{package_surface}}
