#include "suite/test_support.hpp"
#include "suite/test_cases.hpp"

using namespace ecosystem_test_support;

int main(int argc, char** argv) {
    if (argc > 1 && std::string(argv[1]) == "--prerelease-install") {
        if (argc > 3) {
            std::cerr << "usage: " << argv[0]
                      << " --prerelease-install [pacman-cache]\n";
            return 2;
        }
        try {
            test_prerelease_installs_in_an_isolated_pacman_root(
                argc == 3 ? fs::absolute(argv[2])
                          : fs::path("/var/cache/pacman/pkg")
            );
            return 0;
        } catch (const std::exception& error) {
            std::cerr << "[failed] prerelease isolated install: "
                      << error.what() << "\n";
            return 1;
        }
    }
    if (argc > 1 && std::string(argv[1]) == "--workspace-conformance") {
        if (argc != 3) {
            std::cerr << "usage: " << argv[0] << " --workspace-conformance <root>\n";
            return 2;
        }
        const auto errors = workspace_conformance_errors(fs::absolute(argv[2]));
        for (const auto& error : errors)
            std::cerr << "[failed] " << error << "\n";
        if (errors.empty())
            std::cout << "workspace conformance passed\n";
        return errors.empty() ? 0 : 1;
    }
    if (argc > 2 || (argc == 2 && std::string(argv[1]).starts_with("--"))) {
        std::cerr << "usage: " << argv[0] << " [test-name-filter]\n";
        return 2;
    }
    const std::vector<std::pair<std::string, std::function<void()>>> tests {
        { "file_writers_report_late_io_failures",
          test_file_writers_report_late_io_failures },
        { "self_manifest_loads", test_self_manifest_loads },
        { "manifest_rejects_unsafe_paths_and_invalid_dependency_graphs",
          test_manifest_rejects_unsafe_paths_and_invalid_dependency_graphs },
        { "owned_paths_reject_symlink_escapes",
          test_owned_paths_reject_symlink_escapes },
        { "owned_paths_allow_internal_symlinks_and_missing_files",
          test_owned_paths_allow_internal_symlinks_and_missing_files },
        { "owned_paths_preflight_mutations_without_changes",
          test_owned_paths_preflight_mutations_without_changes },
        { "owned_paths_preflight_sync_and_manifest_destinations",
          test_owned_paths_preflight_sync_and_manifest_destinations },
        { "manifest_rejects_generated_test_collisions",
          test_manifest_rejects_generated_test_collisions },
        { "authored_artifacts_round_trip_and_mutate",
          test_authored_artifacts_round_trip_and_mutate },
        { "qml_modules_preserve_optional_ownership_and_generation",
          test_qml_modules_preserve_optional_ownership_and_generation },
        { "authored_artifacts_reject_obsolete_and_ambiguous_intent",
          test_authored_artifacts_reject_obsolete_and_ambiguous_intent },
        { "owned_test_targets_are_independent",
          test_owned_test_targets_are_independent },
        { "owned_scope_discovery_and_build",
          test_owned_scope_discovery_and_build },
        { "manifest_rejects_output_and_target_collisions",
          test_manifest_rejects_output_and_target_collisions },
        { "installed_libraries_are_relocatable",
          test_installed_libraries_are_relocatable },
        { "install_artifacts_build_and_install_independent_executables",
          test_install_artifacts_build_and_install_independent_executables },
        { "visitor_facade_tracks_selected_artifact",
          test_visitor_facade_tracks_selected_artifact },
        { "visitor_facade_handles_runtime_output_layouts",
          test_visitor_facade_handles_runtime_output_layouts },
        { "visitor_facade_rejects_conflicting_output_names",
          test_visitor_facade_rejects_conflicting_output_names },
        { "sync_matches_tracked_surfaces", test_sync_matches_tracked_surfaces },
        { "package_surface_includes_qttest_component",
          test_package_surface_includes_qttest_component },
        { "tracked_facade_limits_surface_to_entry_artifact_closure",
          test_tracked_facade_limits_surface_to_entry_artifact_closure },
        { "external_project_generates_imported_library",
          test_external_project_generates_imported_library },
        { "source_dependency_local_override_builds_and_installs_before_"
          "consumer",
          test_source_dependency_local_override_builds_and_installs_before_consumer },
        { "source_dependency_repository_selection_is_stable_and_explicit",
          test_source_dependency_repository_selection_is_stable_and_explicit },
        { "source_dependency_consumer_exports_are_relocatable",
          test_source_dependency_consumer_exports_are_relocatable },
        { "source_dependency_shared_and_interface_usage_requirements",
          test_source_dependency_shared_and_interface_usage_requirements },
        { "source_dependency_rejects_invalid_provider_contracts_before_"
          "consumer_configure",
          test_source_dependency_rejects_invalid_provider_contracts_before_consumer_configure },
        { "source_dependency_rejects_ambiguous_authored_metadata",
          test_source_dependency_rejects_ambiguous_authored_metadata },
        { "library_facade_installs_library_target_and_headers",
          test_library_facade_installs_library_target_and_headers },
        { "interface_library_facade_installs_headers_without_target",
          test_interface_library_facade_installs_headers_without_target },
        { "runnable_facade_skips_linked_static_library_install_surface",
          test_runnable_facade_skips_linked_static_library_install_surface },
        { "runnable_facade_installs_linked_shared_library_closure",
          test_runnable_facade_installs_linked_shared_library_closure },
        { "project_assets_are_staged_and_installed",
          test_project_assets_are_staged_and_installed },
        { "android_application_id_is_manifest_owned",
          test_android_application_id_is_manifest_owned },
        { "android_environment_selection_is_explicit_and_reported",
          test_android_environment_selection_is_explicit_and_reported },
        { "developer_surface_materializes_full_build_graph",
          test_developer_surface_materializes_full_build_graph },
        { "forbidden_repository_entries_report_legacy_scaffolding",
          test_forbidden_repository_entries_report_legacy_scaffolding },
        { "forbidden_repository_entries_fall_back_for_gitlink_roots",
          test_forbidden_repository_entries_fall_back_for_gitlink_roots },
        { "component_package_link_targets_include_qttest_target",
          test_component_package_link_targets_include_qttest_target },
        { "component_package_link_targets_include_cxxopts_target",
          test_component_package_link_targets_include_cxxopts_target },
        { "component_package_link_targets_follow_descriptor_rules",
          test_component_package_link_targets_follow_descriptor_rules },
        { "summarize_dependencies_follows_descriptor_sources",
          test_summarize_dependencies_follows_descriptor_sources },
        { "summarize_dependencies_collects_cxxopts_stack_values",
          test_summarize_dependencies_collects_cxxopts_stack_values },
        { "declared_package_sections_group_kde_by_profile",
          test_declared_package_sections_group_kde_by_profile },
        { "configured_package_sections_report_component_and_profile_state",
          test_configured_package_sections_report_component_and_profile_state },
        { "package_descriptors_bind_dependency_ids",
          test_package_descriptors_bind_dependency_ids },
        { "package_descriptors_bind_rule_types",
          test_package_descriptors_bind_rule_types },
        { "registered_packages_keep_stable_order",
          test_registered_packages_keep_stable_order },
        { "enabled_surface_blocks_deduplicate_kde_block",
          test_enabled_surface_blocks_deduplicate_kde_block },
        { "dependency_entry_for_id_returns_matching_entry",
          test_dependency_entry_for_id_returns_matching_entry },
        { "package_surface_block_order_is_stable",
          test_package_surface_block_order_is_stable },
        { "package_group_heading_is_stable",
          test_package_group_heading_is_stable },
        { "configured_status_for_package_reports_profile_disabled_kde",
          test_configured_status_for_package_reports_profile_disabled_kde },
        { "configured_status_for_package_requires_all_jni_cache_keys",
          test_configured_status_for_package_requires_all_jni_cache_keys },
        { "configured_status_for_package_detects_cxxopts_dir",
          test_configured_status_for_package_detects_cxxopts_dir },
        { "find_package_surface_rule_returns_qt_rule",
          test_find_package_surface_rule_returns_qt_rule },
        { "render_package_surface_block_keeps_header_only_json_cross_"
          "compilable",
          test_render_package_surface_block_keeps_header_only_json_cross_compilable },
        { "render_package_surface_block_renders_kde_support",
          test_render_package_surface_block_renders_kde_support },
        { "render_package_surface_block_renders_qt_support",
          test_render_package_surface_block_renders_qt_support },
        { "render_package_surface_block_renders_llvm_support",
          test_render_package_surface_block_renders_llvm_support },
        { "render_package_surface_block_renders_opencv_support",
          test_render_package_surface_block_renders_opencv_support },
        { "render_package_surface_block_renders_cxxopts_support",
          test_render_package_surface_block_renders_cxxopts_support },
        { "workspace_conformance_reports_all_projects",
          test_workspace_conformance_reports_all_projects },
        { "tracked_surface_generation_uses_github_vars_file",
          test_tracked_surface_generation_uses_github_vars_file },
        { "tracked_surface_generation_supports_remote_setup_action",
          test_tracked_surface_generation_supports_remote_setup_action },
        { "sync_project_removes_obsolete_tracked_surface_files",
          test_sync_project_removes_obsolete_tracked_surface_files },
        { "required_template_failures_preserve_generated_state",
          test_required_template_failures_preserve_generated_state },
        { "required_developer_template_failure_is_reported",
          test_required_developer_template_failure_is_reported },
        { "required_missing_and_unreadable_templates_fail",
          test_required_missing_and_unreadable_templates_fail },
        { "mutate_add_module_updates_manifest_and_files",
          test_mutate_add_module_updates_manifest_and_files },
        { "ci_stage_reports_intermediate_and_pipeline_failures",
          test_ci_stage_reports_intermediate_and_pipeline_failures },
        { "ci_required_result_enforces_failures_and_missing_evidence",
          test_ci_required_result_enforces_failures_and_missing_evidence },
        { "github_bootstrap_vars_validate_explicit_selection",
          test_github_bootstrap_vars_validate_explicit_selection },
        { "ci_bootstrap_builds_reviewed_checkout_and_repository_layouts",
          test_ci_bootstrap_builds_reviewed_checkout_and_repository_layouts },
        { "ci_bootstrap_rejects_missing_inputs_and_escaping_layouts",
          test_ci_bootstrap_rejects_missing_inputs_and_escaping_layouts },
        { "installed_actors_use_their_template_bundle",
          test_installed_actors_use_their_template_bundle },
        { "doxygen_configuration_uses_exact_ownership_and_service_state",
          test_doxygen_configuration_uses_exact_ownership_and_service_state },
        { "cli_doxygen_generates_native_scoped_documentation",
          test_cli_doxygen_generates_native_scoped_documentation },
        { "cli_doxy_propagates_native_graphviz_errors_with_zero_tool_exit",
          test_cli_doxy_propagates_native_graphviz_errors_with_zero_tool_exit },
        { "cli_doxy_retains_tool_failures_and_requires_fresh_output",
          test_cli_doxy_retains_tool_failures_and_requires_fresh_output },
        { "cli_doxy_rejects_service_output_aliases_before_writing",
          test_cli_doxy_rejects_service_output_aliases_before_writing },
        { "cli_workspace_doxy_keeps_selected_artifact_outputs_separate",
          test_cli_workspace_doxy_keeps_selected_artifact_outputs_separate },
        { "cli_check_doxy_rejects_failed_configuration",
          test_cli_check_doxy_rejects_failed_configuration },
        { "template_loader_renders_repo_owned_templates",
          test_template_loader_renders_repo_owned_templates },
        { "ensure_local_artifacts_keeps_tracked_style_surfaces_sync_owned",
          test_ensure_local_artifacts_keeps_tracked_style_surfaces_sync_owned },
        { "mutate_add_component_scaffolds_templates",
          test_mutate_add_component_scaffolds_templates },
        { "mutate_add_component_supports_custom_artifact_ids_and_links",
          test_mutate_add_component_supports_custom_artifact_ids_and_links },
        { "mutate_add_component_infers_facade_library_closure",
          test_mutate_add_component_infers_facade_library_closure },
        { "mutate_add_component_infers_facade_component_library_closure",
          test_mutate_add_component_infers_facade_component_library_closure },
        { "mutate_add_component_infers_direct_runnable_library_links",
          test_mutate_add_component_infers_direct_runnable_library_links },
        { "mutate_add_file_unit_supports_h_variants",
          test_mutate_add_file_unit_supports_h_variants },
        { "cli_mutate_add_component_supports_artifact_id_and_link_options",
          test_cli_mutate_add_component_supports_artifact_id_and_link_options },
        { "cli_list_artifacts", test_cli_list_artifacts },
        { "cli_actor_batches_preserve_ownership",
          test_cli_actor_batches_preserve_ownership },
        { "cli_actor_help_and_queue_validation",
          test_cli_actor_help_and_queue_validation },
        { "cli_all_operations_have_one_actor",
          test_cli_all_operations_have_one_actor },
        { "cli_engels_rejects_marx_commands",
          test_cli_engels_rejects_marx_commands },
        { "cli_marx_rejects_engels_commands",
          test_cli_marx_rejects_engels_commands },
        { "cli_report_matrix", test_cli_report_matrix },
        { "cli_workspace_list", test_cli_workspace_list },
        { "invalid_workspace_projects_remain_visible",
          test_invalid_workspace_projects_remain_visible },
        { "invalid_workspace_group_and_root_manifest",
          test_invalid_workspace_group_and_root_manifest },
        { "cli_workspace_list_groups", test_cli_workspace_list_groups },
        { "cli_workspace_group_filter_selects_configured_projects",
          test_cli_workspace_group_filter_selects_configured_projects },
        { "cli_workspace_report_matrix_records_group_selection",
          test_cli_workspace_report_matrix_records_group_selection },
        { "cli_workspace_group_filter_rejects_unknown_groups",
          test_cli_workspace_group_filter_rejects_unknown_groups },
        { "cli_workspace_config_rejects_unknown_group_project_selector",
          test_cli_workspace_config_rejects_unknown_group_project_selector },
        { "cli_workspace_report_matrix", test_cli_workspace_report_matrix },
        { "cli_workspace_build_on_sample_workspace",
          test_cli_workspace_build_on_sample_workspace },
        { "cli_workspace_build_supports_multiple_artifact_filters",
          test_cli_workspace_build_supports_multiple_artifact_filters },
        { "cli_workspace_sync_supports_project_filter",
          test_cli_workspace_sync_supports_project_filter },
        { "cli_workspace_sync_supports_multi_project_filter",
          test_cli_workspace_sync_supports_multi_project_filter },
        { "cli_workspace_report_matrix_supports_filters",
          test_cli_workspace_report_matrix_supports_filters },
        { "cli_workspace_report_matrix_supports_multiple_artifact_filters",
          test_cli_workspace_report_matrix_supports_multiple_artifact_filters },
        { "cli_workspace_report_matrix_supports_multi_project_filters",
          test_cli_workspace_report_matrix_supports_multi_project_filters },
        { "cli_workspace_unqualified_artifact_filter_rejects_multi_project_"
          "selection",
          test_cli_workspace_unqualified_artifact_filter_rejects_multi_project_selection },
        { "cli_run_executes_facade_entry", test_cli_run_executes_facade_entry },
        { "cli_run_executes_requested_artifact_with_passthrough_args",
          test_cli_run_executes_requested_artifact_with_passthrough_args },
        { "cli_workspace_run_executes_selected_project",
          test_cli_workspace_run_executes_selected_project },
        { "cli_workspace_run_rejects_multiple_artifact_filters",
          test_cli_workspace_run_rejects_multiple_artifact_filters },
        { "cli_workspace_check_ci_rejects_multiple_artifact_filters",
          test_cli_workspace_check_ci_rejects_multiple_artifact_filters },
        { "cli_run_android_deploys_selected_artifact",
          test_cli_run_android_deploys_selected_artifact },
        { "cli_check_naming_reports_identifier_overflow_and_honors_allowlist",
          test_cli_check_naming_reports_identifier_overflow_and_honors_allowlist },
        { "personal_naming_uses_declarations_and_exact_policy_boundaries",
          test_personal_naming_uses_declarations_and_exact_policy_boundaries },
        { "personal_naming_reports_analysis_failures_and_owned_headers",
          test_personal_naming_reports_analysis_failures_and_owned_headers },
        { "personal_style_measures_control_bodies_and_local_scopes",
          test_personal_style_measures_control_bodies_and_local_scopes },
        { "personal_style_indexes_referents_and_measures_volume_without_size_"
          "gates",
          test_personal_style_indexes_referents_and_measures_volume_without_size_gates },
        { "cli_personal_style_preserves_workspace_scope_and_failure_status",
          test_cli_personal_style_preserves_workspace_scope_and_failure_status },
        { "cli_check_leaks_runs_sanitized_tests",
          test_cli_check_leaks_runs_sanitized_tests },
        { "cli_check_tidy_uses_clang_tidy_when_available",
          test_cli_check_tidy_uses_clang_tidy_when_available },
        { "cli_check_tidy_fails_when_clang_tidy_reports_diagnostics",
          test_cli_check_tidy_fails_when_clang_tidy_reports_diagnostics },
        { "tidy_requires_tool_and_complete_compilation_database",
          test_tidy_requires_tool_and_complete_compilation_database },
        { "cli_check_tidy_honors_full_artifact_identity_and_configuration",
          test_cli_check_tidy_honors_full_artifact_identity_and_configuration },
        { "cli_build_release_uses_release_build_type",
          test_cli_build_release_uses_release_build_type },
        { "build_tree_layout_nests_project_and_probe_profiles",
          test_build_tree_layout_nests_project_and_probe_profiles },
        { "render_benchmark_svg_uses_template_backed_surface",
          test_render_benchmark_svg_uses_template_backed_surface },
        { "cli_format_shares_verifier_selection_and_tool",
          test_cli_format_shares_verifier_selection_and_tool },
        { "cli_workspace_format_respects_selected_projects_and_artifacts",
          test_cli_workspace_format_respects_selected_projects_and_artifacts },
        { "cli_benchmark_accepts_generic_programs_and_preserves_results",
          test_cli_benchmark_accepts_generic_programs_and_preserves_results },
        { "cli_benchmark_builds_release_benchmarks_and_writes_reports",
          test_cli_benchmark_builds_release_benchmarks_and_writes_reports },
        { "prerelease_command_log_preserves_output_and_fails_closed",
          test_prerelease_command_log_preserves_output_and_fails_closed },
        { "cli_prerelease_retains_attempt_logs_and_summaries",
          test_cli_prerelease_retains_attempt_logs_and_summaries },
        { "cli_prerelease_rejects_unusable_attempt_storage",
          test_cli_prerelease_rejects_unusable_attempt_storage },
        { "cli_prerelease_builds_shareable_repos_and_auto_increments_version",
          test_cli_prerelease_builds_shareable_repos_and_auto_increments_version },
        { "prerelease_packages_linked_runtime_closure",
          test_prerelease_packages_linked_runtime_closure },
        { "prerelease_maps_native_dependencies_and_preserves_state_on_query_"
          "failures",
          test_prerelease_maps_native_dependencies_and_preserves_state_on_query_failures },
        { "prerelease_packages_installed_source_provider_runtime",
          test_prerelease_packages_installed_source_provider_runtime },
        { "prerelease_runtime_failures_preserve_previous_release",
          test_prerelease_runtime_failures_preserve_previous_release },
        { "prerelease_retains_soname_aliases_and_rejects_runtime_conflicts",
          test_prerelease_retains_soname_aliases_and_rejects_runtime_conflicts },
        { "prerelease_tooling_archives_carry_their_template_bundle",
          test_prerelease_tooling_archives_carry_their_template_bundle },
        { "prerelease_rejects_missing_or_aliased_tooling_data",
          test_prerelease_rejects_missing_or_aliased_tooling_data },
        { "prerelease_respects_asset_install_intent",
          test_prerelease_respects_asset_install_intent },
        { "prerelease_preserves_published_state_on_late_failures",
          test_prerelease_preserves_published_state_on_late_failures },
        { "prerelease_retains_recovery_state_and_rejects_publication_aliases",
          test_prerelease_retains_recovery_state_and_rejects_publication_aliases },
        { "prerelease_rejects_colliding_install_payloads",
          test_prerelease_rejects_colliding_install_payloads },
        { "cli_prerelease_includes_install_companions",
          test_cli_prerelease_includes_install_companions },
        { "cli_prerelease_signs_repo_metadata_when_requested",
          test_cli_prerelease_signs_repo_metadata_when_requested },
        { "cli_check_java_builds_shared_libraries_and_runs_gradle_tests",
          test_cli_check_java_builds_shared_libraries_and_runs_gradle_tests },
        { "cli_check_sphinx_generates_local_conf_with_rtd_theme",
          test_cli_check_sphinx_generates_local_conf_with_rtd_theme },
        { "cli_check_sphinx_theme_flag_sets_theme_override",
          test_cli_check_sphinx_theme_flag_sets_theme_override },
        { "cli_check_repo_rejects_legacy_repository_entries",
          test_cli_check_repo_rejects_legacy_repository_entries },
        { "cli_check_repo_rejects_tracked_surface_drift",
          test_cli_check_repo_rejects_tracked_surface_drift },
        { "cli_workspace_check_repo_rejects_gitlink_project_scripts",
          test_cli_workspace_check_repo_rejects_gitlink_project_scripts },
        { "generated_builds_reject_compiler_warnings_in_c_and_cxx",
          test_generated_builds_reject_compiler_warnings_in_c_and_cxx },
        { "cli_required_checks_propagate_failures_and_reject_empty_ctest_runs",
          test_cli_required_checks_propagate_failures_and_reject_empty_ctest_runs },
        { "cli_check_ci_fails_fast_on_repository_policy_drift",
          test_cli_check_ci_fails_fast_on_repository_policy_drift },
        { "cli_doctor_reports_declared_dependency_guidance",
          test_cli_doctor_reports_declared_dependency_guidance },
        { "cli_doctor_artifact_scope_filters_declared_dependencies",
          test_cli_doctor_artifact_scope_filters_declared_dependencies },
        { "cli_doctor_reports_configured_package_state_from_cache",
          test_cli_doctor_reports_configured_package_state_from_cache },
        { "cli_doctor_artifact_scope_filters_configured_package_state",
          test_cli_doctor_artifact_scope_filters_configured_package_state },
        { "cli_doctor_uses_requested_kde_cache_for_package_state",
          test_cli_doctor_uses_requested_kde_cache_for_package_state },
        { "cli_doctor_reports_tracked_surface_drift",
          test_cli_doctor_reports_tracked_surface_drift },
        { "cli_doctor_materializes_missing_configure_cache",
          test_cli_doctor_materializes_missing_configure_cache },
        { "cli_doctor_refreshes_stale_configure_cache",
          test_cli_doctor_refreshes_stale_configure_cache },
        { "cli_doctor_artifact_scope_refresh_uses_scoped_probe_cache",
          test_cli_doctor_artifact_scope_refresh_uses_scoped_probe_cache },
        { "cli_doctor_refreshes_stale_configure_state_without_cache_changes",
          test_cli_doctor_refreshes_stale_configure_state_without_cache_changes },
        { "cli_report_cxx_preserves_artifact_scope_and_failure_status",
          test_cli_report_cxx_preserves_artifact_scope_and_failure_status },
        { "cli_workspace_report_cxx_preserves_each_selected_owner",
          test_cli_workspace_report_cxx_preserves_each_selected_owner },
        { "cli_personal_reports_share_findings_and_presentation",
          test_cli_personal_reports_share_findings_and_presentation },
        { "cli_workspace_personal_reports_keep_all_selected_results",
          test_cli_workspace_personal_reports_keep_all_selected_results },
        { "clang_analysis_reports_unusable_inputs",
          test_clang_analysis_reports_unusable_inputs },
        { "clang_analysis_runs_on_sample_project",
          test_clang_analysis_runs_on_sample_project },
        { "clang_analysis_skips_benchmarks_and_generated_sources_by_default",
          test_clang_analysis_skips_benchmarks_and_generated_sources_by_default },
        { "clang_analysis_includes_benchmark_component_when_requested",
          test_clang_analysis_includes_benchmark_component_when_requested },
    };

    int failures = 0;
    int selected = 0;
    for (const auto& [name, test] : tests) {
        if (argc > 1 && name.find(argv[1]) == std::string::npos) {
            continue;
        }
        ++selected;
        try {
            test();
            std::cout << "[ok] " << name << "\n";
        } catch (const std::exception& error) {
            ++failures;
            std::cerr << "[failed] " << name << ": " << error.what() << "\n";
        }
    }

    if (selected == 0) {
        std::cerr << "no tests match the requested filter\n";
        return 1;
    }
    return failures == 0 ? 0 : 1;
}
